### ISSUE TITLE
Gastgezinnen op (tijdelijk) niet beschikbaar zetten

### ISSUE THREAD

**Issue by sjerpbouwtsites** [sjerpbouwtsites/blijfvanmijndier#36]
onbeschikbaar modus: 1u
    tijdelijk onbeschikbaar van-tot modus: 3u
    niet meenemen in kaart: 30m
    visualisatie in maya: 3 aparte tabblaadjes: beschikbaar, tijdelijk niet beschikbaar, onbeschikbaar. 2u

**Comment by sjerpbouwtsites** [comment]
https://ttprivatenew.s3.amazonaws.com/pulse/ik-sjerpvanwouden/attachments/17368843/TinyTake04-07-2021-09-50-05.mp4

**Comment by sjerpbouwtsites** [comment]
https://ik-sjerpvanwouden.tinytake.com/tt/NTU4NDIyOV8xNzM3NTc4OQ
@RenildeMendoo de GG onbeschikbaar staat klaar

**Comment by sjerpbouwtsites** [comment]
Ik maak nu echt grote fouten. Shit. Teveel door elkaar.

**Comment by RenildeMendoo** [comment]
Maar hij staat er nu wel op toch? Ik ga gewoon lekker comments schrijven. Ten eerste natuurlijk: super veeeet! Dankjewel!

Punt 1: Wat super handig dat we nu direct iets kunnen kopieëren met een knopje. Zou je dat knopje ook kunnen maken voor het adres kopieëren? Dat zou echt ideaal zijn!

**Comment by RenildeMendoo** [comment]
Punt 2: is het ook mogelijk om een GG helemaal af te melden? Of kan dat alleen door in te vullen dat een gastgezin tot, zeg, 2050 niet beschikbaar is?

**Comment by RenildeMendoo** [comment]
Punt 3: Beschikbaarheid tonen op pagina van GG
Ik heb als voorbeeld bij GG Arnout (http://10.123.2.84:8080/guests/25) ingevuld dat hij eind juli t/m begin augustus niet beschikbaar is. Dat staat nu alleen in het overzicht op de beginpagina (http://10.123.2.84:8080/guests), maar niet op zijn eigen pagina. Dat lijkt wat onhandig. Zou je ook op de pagina van het GG kunnen laten zien wanneer iemand niet/wel beschikbaar is?

**Comment by RenildeMendoo** [comment]
Punt 4: Tabblad beschikbare GG op alfabetische volgorde

Dit tabblad met beschikbare GG heb je nu volgens mij op een volgorde gezet qua tijd, maar ik denk dat het makkelijker is om dit tabblad alfabetisch te houden. Of had je een bepaalde reden waarom dit niet alfabetisch is?

**Comment by RenildeMendoo** [comment]
Punt 5: gekke bug als je datum onbeschikbaarheid niet invult
Als je bij een GG-pagina het vinkje 'onbeschikbaar' aan klikt, geen datum invult en op opslaan klikt, krijg je een foutmelding. Logisch natuurlijk. Als je vervolgens op vorige pagina klikt, werkt het vinkje 'onbeschikbaar' niet meer goed. Als je dan het vinkje selecteert, verdwijnen de begin- einddatum. En als je het vinkje deselcteert, verschijnen de begin- en einddatum. 
Dit gaat weg als je de hele pagina vernieuwt.

**Comment by sjerpbouwtsites** [comment]
> Maar hij staat er nu wel op toch? Ik ga gewoon lekker comments schrijven. Ten eerste natuurlijk: super veeeet! Dankjewel!
> 
> Punt 1: Wat super handig dat we nu direct iets kunnen kopieëren met een knopje. Zou je dat knopje ook kunnen maken voor het adres kopieëren? Dat zou echt ideaal zijn!

Dit zet ik ook in een andere issue.

**Comment by sjerpbouwtsites** [comment]
> Punt 2: is het ook mogelijk om een GG helemaal af te melden? Of kan dat alleen door in te vullen dat een gastgezin tot, zeg, 2050 niet beschikbaar is?

**Comment by sjerpbouwtsites** [comment]
> Punt 3: Beschikbaarheid tonen op pagina van GG
> Ik heb als voorbeeld bij GG Arnout (http://10.123.2.84:8080/guests/25) ingevuld dat hij eind juli t/m begin augustus niet beschikbaar is. Dat staat nu alleen in het overzicht op de beginpagina (http://10.123.2.84:8080/guests), maar niet op zijn eigen pagina. Dat lijkt wat onhandig. Zou je ook op de pagina van het GG kunnen laten zien wanneer iemand niet/wel beschikbaar is?

Als een GG momenteel niet beschikbaar is, dan verschijnt een tekst bovenaan de pagina die dat aangeeft. Ik zal ook een bijkomende tekst naast diervoorkeur oid zetten.

**Comment by sjerpbouwtsites** [comment]
> Punt 4: Tabblad beschikbare GG op alfabetische volgorde
> 
> Dit tabblad met beschikbare GG heb je nu volgens mij op een volgorde gezet qua tijd, maar ik denk dat het makkelijker is om dit tabblad alfabetisch te houden. Of had je een bepaalde reden waarom dit niet alfabetisch is?

Ja, Dit is niet alfabetisch omdat het gaat om het vinden van beschikbare GG. Ze zijn niet in gelijke mate beschikbaar. Dus de GGs die maar kort beschikbaar zijn staan achteraan en de GG die goed beschikbaar zijn staan vooraan.

**Comment by sjerpbouwtsites** [comment]
> Punt 5: gekke bug als je datum onbeschikbaarheid niet invult
> Als je bij een GG-pagina het vinkje 'onbeschikbaar' aan klikt, geen datum invult en op opslaan klikt, krijg je een foutmelding. Logisch natuurlijk. Als je vervolgens op vorige pagina klikt, werkt het vinkje 'onbeschikbaar' niet meer goed. Als je dan het vinkje selecteert, verdwijnen de begin- einddatum. En als je het vinkje deselcteert, verschijnen de begin- en einddatum.
> Dit gaat weg als je de hele pagina vernieuwt.

Gefikst, andere bug gevonden; mag niet aanvankelijk opslaan zonder onbeschikbaarheids status. Zal fiksen.

**Comment by sjerpbouwtsites** [comment]
En dit staat er ook helemaal klaar voor.

**Comment by RenildeMendoo** [comment]
Joehoeeeee leuk leuk!

we hebben vanuit het team een aantal opmerkingen:

1) Er staat nu steeds onbeschikbaar, maar dat is geen woord. Zou je dat kunnen veranderen naar 'niet beschikbaar'? Ook in de tabbladen bijv, maar ook op de pagina van een GG wijzigen:
![image](https://user-images.githubusercontent.com/86714970/125445542-662ae914-dbba-4841-b6cf-0e3c89ef646a.png)

2) Op de overzichtspagina van GG staat het logootje voor telefoonnummer kopiëren niet zo mooi gepostioneerd:
![image](https://user-images.githubusercontent.com/86714970/125445630-ed497efd-3784-45db-8441-0306d93638ad.png)

Geen prio: Kan dit ook in het Nederlands? :p 
![image](https://user-images.githubusercontent.com/86714970/125445670-9da61b47-ac37-48ec-9dc3-34dddb4e591d.png)

**Comment by RenildeMendoo** [comment]
Ooooh we hebben ook twee 'echte' bugs gevonden @sjerpbouwtsites!

1) Opmerking GG wijzigen lukt niet meer op de pagina van een GG
Sommige GG kunnen wel gewijzigd worden (zoals Ad Hemelrijk), maar Petra Verstegen en Angelique v/d Gaag dan weer niet. 

![image](https://user-images.githubusercontent.com/86714970/125445898-0fd67045-a5d7-47dc-a33f-ddd1858170f3.png)

En dan krijgen we deze melding:
![image](https://user-images.githubusercontent.com/86714970/125445936-ad0c51f5-c69f-4103-9dd1-fe6dbdb117db.png)

**Comment by RenildeMendoo** [comment]
En 2. bij GG kunnen we niet aanvinken welke eigen dieren ze hebben

![image](https://user-images.githubusercontent.com/86714970/125446110-dddcbe3b-f07c-4159-ad1e-d3003f94562e.png)

met deze foutmelding:

![image](https://user-images.githubusercontent.com/86714970/125446133-898537b4-21ae-42fc-917c-4641e35d40b8.png)

**Comment by sjerpbouwtsites** [comment]
> Geen prio: Kan dit ook in het Nederlands? :p
> ![image](https://user-images.githubusercontent.com/86714970/125445670-9da61b47-ac37-48ec-9dc3-34dddb4e591d.png)

ja, dat kan, daar had ik al wel wat tijd tegen aan gegooid en niet zo snel uitgekomen. Nederlands zou beter zijn.
