### ISSUE TITLE
 Updates voor meerdere dieren linken

### ISSUE THREAD

**Issue by sjerpbouwtsites** [sjerpbouwtsites/blijfvanmijndier#38]
Als je een update aanmaakt, van een dier, is een multiselect aanwezig met alle dieren van die eigenaar. Hier kan je meerdere dieren selecteren met de optie 'kloon update naar dieren'.
4u

**Comment by sjerpbouwtsites** [comment]
![afbeelding](https://user-images.githubusercontent.com/34159539/124424392-3d046400-dd67-11eb-92ec-8b3962a901f1.png)

Zo. https://github.com/sjerpbouwtsites/blijfvanmijndier/tree/dev_updates-multi-dier. Staat ook klaar.

**Comment by sjerpbouwtsites** [comment]
![afbeelding](https://user-images.githubusercontent.com/34159539/124485673-1b2dd000-ddad-11eb-95b7-8b20ab8daf9b.png)
@RenildeMendoo lol

**Comment by sjerpbouwtsites** [comment]
@RenildeMendoo  het staat op staging. Ik krijg een raar gevoel dat er wat mis gaat bij het ophalen van de dieren die bij die of gene horen.

**Comment by sjerpbouwtsites** [comment]
@RenildeMendoo bovenstaande melding klopte. Er ontbrak telkens een dier... namelijk het originele dier. Dat is nu gefikst.

**Comment by RenildeMendoo** [comment]
Yeahhh cool dat het gelukt is! Er vallen me twee punten op (die doe ik even in losse comments, geen idee of dat handig is?)

Punt 1: Er zijn gekke koppelingen
Ik was net even aan het testen bij Angel door een update bij haar toe te voegen, maar ik zie dan staan dat de katten Guus & Gert ook daar op de een of andere manier aan gekoppeld zijn. Maar zover ik weet, hebben Angel en Guus & Gert niets met elkaar te maken, heb jij een idee waar dit dan vandaan komt? 
![image](https://user-images.githubusercontent.com/86714970/124775774-303a6880-df3f-11eb-8453-12222d15013c.png)

Ook zie ik bijvoorbeeld bij Guus gastgezin Pine Remmelts gelinkt staan. Dat klopt. Maar dan staat vervolgens bij Pine Remmelts weer Ganya en Sky gelinkt. Die twee dieren hebben weer niets met GG Pine te maken. Hoe kan dat? 
![image](https://user-images.githubusercontent.com/86714970/124776113-78598b00-df3f-11eb-85e5-03cc2a27112c.png)

**Comment by RenildeMendoo** [comment]
Punt 2: updates toevoegen bij GG 

We zouden graag bij het gastgezin zélf een update willen distrubueren. Dus in het voorbeeld bij Pine met Guus & Gert: We hebben een update-tekst: 'We hebben met het GG gesproken en zij wil heel graag weer voor ons opvangen als Guus en Gert naar huis zijn'. Deze update willen we dan bij Guus & Gert krijgen (dat lukt nu tegelijk, dat werkt super goed!), maar óók nog bij het GG zelf (dus op deze pagina: http://10.123.2.84:8080/guests/159 onder updates. 

![image](https://user-images.githubusercontent.com/86714970/124778120-041fe700-df41-11eb-8037-b272c8d8d97d.png)

![image](https://user-images.githubusercontent.com/86714970/124778299-2a458700-df41-11eb-92b8-13ffec65aae8.png)

**Comment by RenildeMendoo** [comment]
Punt 3: Update eigenaar distribueren naar zijn/haar dieren
Is het mogelijk om de update van een eigenaar te distrubueren naar zijn/haar dieren? 
Dus bij eigenaar Pascal (eigenaar van Guus en Gert); dat je die update direct kan koppelen aan Guus & Gert? 
Of hadden we t hier juist over gehad, dat dat eigenlijk te moeilijk is?

![image](https://user-images.githubusercontent.com/86714970/124780464-e94e7200-df42-11eb-9262-667f53a7875a.png)

**Comment by sjerpbouwtsites** [comment]
> Punt 1: Er zijn gekke koppelingen

Classic fok op. Goed gezien. Ik pak die nu op.

**Comment by sjerpbouwtsites** [comment]
gevondennnnnn
![image](https://user-images.githubusercontent.com/34159539/125243436-66d10400-e2ee-11eb-9685-d7da74731c77.png)

**Comment by sjerpbouwtsites** [comment]
Dit ziet er goed uit en staat op staging

**Comment by RenildeMendoo** [comment]
We hebben hier twee opmerkingen:

1. 'Update distribueren' --> kan je deze tekst veranderen naar ‘updates dupliceren’? We vinden distribueren een lastig woord ;)
2. Deze had ik al eerder genoemed; updates dupliceren naar eigenaren & GG (die staat ook al in een andere opmerking zag ik)

Met deze optie is het team zó super blij! Dankjewel!
(ik had 'm net per ongeluk bij 't verkeerde onderwerp gezet, excuus!)

**Comment by RenildeMendoo** [comment]
Goedemorgen Sjerp! Ik was erg benieuwd naar de 'nieuwe' Maya dus ben meteen maar even gaan kijken :)

Dit viel me op:
Bij het dupliceren van een update, staat alleen nog de uitleg, niet meer de optie om dieren aan te vinken:

![image](https://user-images.githubusercontent.com/86714970/125906010-a2371126-1885-4def-9b4d-314781873500.png)

**Comment by RenildeMendoo** [comment]
En nog een BUG gevonden (ik doe even bij de belangrijke dingen zo BUG, hopelijk is dat handig?)

We kunnen dieren niet meer koppelen aan een GG; normaal doen we dat via deze pagina en dan op 'zoek gastgezin':

![image](https://user-images.githubusercontent.com/86714970/125910779-55cafd92-67e3-4d31-bcfd-8027685cec0f.png)



We krijgen dan deze melding:

![image](https://user-images.githubusercontent.com/86714970/125910713-b29758d9-971a-42cf-a865-b4971fb60371.png)

**Comment by sjerpbouwtsites** [comment]
> 
> we kunnen dieren niet meer koppelen

@RenildeMendoo is dit momenteel nog zo?

**Comment by sjerpbouwtsites** [comment]
> Bij het dupliceren van een update, staat alleen nog de uitleg, niet meer de optie om dieren aan te vinken:

momenteel ziet het er bij mij lokaal zo uit: 
![afbeelding](https://user-images.githubusercontent.com/34159539/130779374-5fceece2-fda1-4d3f-ba57-5ada9d5df16a.png)

**Comment by sjerpbouwtsites** [comment]
En op de staging zie ik qua updates dupliceren bij bear ook de functionaliteit die ik verwacht. 
![afbeelding](https://user-images.githubusercontent.com/34159539/130779921-b4fea129-c863-4e77-90e2-2adb0357a3ca.png)
@RenildeMendoo 

Ik geloof dat dit issue dus afgerond is. Ik sluit hem dan ten behoeve van het overzicht.

**Comment by RenildeMendoo** [comment]
> > we kunnen dieren niet meer koppelen
> 
> @RenildeMendoo is dit momenteel nog zo?
> Momenteel kan ik het wel.

Dit lukt ons ook, volgens mij had je dit vrij snel opgepakt!

**Comment by RenildeMendoo** [comment]
> En op de staging zie ik qua updates dupliceren bij bear ook de functionaliteit die ik verwacht.
> ![afbeelding](https://user-images.githubusercontent.com/34159539/130779921-b4fea129-c863-4e77-90e2-2adb0357a3ca.png)
> @RenildeMendoo
> 
> Ik geloof dat dit issue dus afgerond is. Ik sluit hem dan ten behoeve van het overzicht.

Yes, klopt! We zijn hier heel blij mee en gebruiken deze functionaliteit ook echt heel vaak!
