### ISSUE TITLE
meldingen over dieren

### ISSUE THREAD

**Issue by sjerpbouwtsites** [sjerpbouwtsites/blijfvanmijndier#39]
EDIT: Wat ik over de mail stuurde was gebaseerd op een tekst uit een mailtje. Die mail snapte ik niet goed. Hier staat de taak duidelijker. Dus ik heb nog niet helemaal het juiste gebouwd. Dit bouw ik nu

Meldingen op Maya
Elke twee maanden een melding dat er contact moet komen met hulpverlening & GG.
En na 10 maanden een melding dat het bijna een jaar is.
-> is dit: lijst met updates vergelijken met actuele datum en kijken welke er in het gevarengebied zitten? Dan: 1 dag.

    tweewekelijkse cyclus. Rood, als update eigenaar > 14 dagen geleden.
    2 maandelijkse cyclus. Paars, als update contact hulpverlening > 60 dagen
    2 maandelijkse cyclus. Geel, als update contact gastgezin > 60 dagen
    na 10 maanden, Zwart als update evaluatie (NIEUWE UPDATE STATUS) > 10 maanden.
    Vooralsnog: laten we 'm rood bij 2 weken.

**Comment by sjerpbouwtsites** [comment]
MELDINGEN
up animals/todo in 4 lijsten, per cycli, in tabblad.

**Comment by sjerpbouwtsites** [comment]
huidige stand van zaken  https://ik-sjerpvanwouden.tinytake.com/tt/NTU0OTQ2MV8xNzI5MjM4OA

**Comment by sjerpbouwtsites** [comment]
![afbeelding](https://user-images.githubusercontent.com/34159539/124249320-0db1e500-db24-11eb-8a76-01dbcdeb058d.png)
Waar we over moesten bellen was oa hoe gaan we om met gast/pension. Dat slaat denk ik op dezelfde soort update, namelijk het verblijf. Maar het zijn 2 aparte updates. Dus die neem ik nu samen en ga er van uit dat een dier ofwel bij een pension of een gastgezin is. Om ruimte te maken heb ik het hartje icoon, dat sloeg op 'er zijn nog helemaal geen updates' eruit gehaald, en vervangen door een huis icoon, slaande op pension/gastgezin.
Verder is het herhalings icoon vervangen. Dat was een klok maar is nu een cirkelpijl

**Comment by RenildeMendoo** [comment]
Test, lukt dit?

**Comment by sjerpbouwtsites** [comment]
@RenildeMendoo je krijgt nu mail van mij

**Comment by RenildeMendoo** [comment]
Alle foto's zijn verdwenen op de staging. Klopt dat? 
Verder heb ik hier geen opmerkingen, vind het er super netjes uit zien!
Ik ga het dinsdag aan collega's laten zien :)

**Comment by sjerpbouwtsites** [comment]
> Alle foto's zijn verdwenen op de staging. Klopt dat?
Ja dat klopt. Dit komt door een eigenaardigheid in hoe afbeeldingen worden opgeslagen. Normaliter sla je afbeeldingen op buiten de locatie met de code. Maar de architectuur is dusdanig dat de afbeeldingen tussen de code zitten. Dus bij het overzetten van code van de ene naar de andere locatie kunnen de afbeeldingen sneuvelen.

**Comment by RenildeMendoo** [comment]
We hebben hier twee opmerkingen:
1) 'Update distribueren' --> kan je deze tekst veranderen naar ‘updates dupliceren’? We vinden distribueren een lastig woord ;)
2) Deze had ik al eerder genoemed; updates dupliceren naar eigenaren & GG (die staat ook al in een andere opmerking zag ik)

Met deze optie is het team zó super blij! Dankjewel!

**Comment by RenildeMendoo** [comment]
Ook mijn collega's vinden het super netjes er uit zien. Echt zooo vet :D 

Onze opmerkingen:
1) Kan je voor de kleurcodes 'onze' Mendoo-kleuren gebruiken? Ik heb de kleurcodes net doorgestuurd. 
2) Kan je op Maya het logo van Mendoo zetten? Ipv het logo van BvmD wat er nu nog staat. Oké, ik besef me dat dit officieel niet bij hoort bij dit onderwerp, ik hoop dat je het me kan vergeven ;)
3) Kan je bij onderstaande teksten het tekstje 'Verblijf vervolg contact' veranderen naar 'verblijf gastgezin/pension vervolg contact'? Dat lijkt ons wat duidelijker werken:
![image](https://user-images.githubusercontent.com/86714970/125444391-eac22733-3190-4e4d-a40a-f8de2466bf61.png)

**Comment by RenildeMendoo** [comment]
Ook bij de 'nieuwe' Maya heb ik hierbij nog een opmerking:

Bij elk dier hebben we de optie 'updates' (hiermee bedoelen we 'tweewekelijkse update', dus het bericht wat elke twee weken naar een eigenaar wordt gestuurd). Deze optie kan wordena aangevinkt, maar dat hoeft niet:

![image](https://user-images.githubusercontent.com/86714970/125906311-e2450f30-67c7-4f72-9bd1-ad060a2ffef2.png)

We hebben deze optie van het aanvinken toegevoegd, omdat eigenaren die met hun dier in een vrouwenopvang verblijven, niet elke twee weken een update hoeven te ontvangen. Zij hebben immers het dier bij zich. Deze eigenaren krijgen dus geen vinkje. Terwijl een dier wat bij een GG verblijft, wél dit vinkje krijgen, zodat we elke twee weken een herinnering krijgen dat ze een update over het dier moeten ontvangen. 

Nu zie ik dat op de nieuwe Maya álle dieren een paars vakje (= tijd voor 'update eigenaar' = 2 wekelijkse update) hebben gekregen. Ook dus de dieren waarbij dit vinkje **niet** is aangevinkt. Zoals Coco & Neel (die van de printscreen hierboven) maar ook Arie:

![image](https://user-images.githubusercontent.com/86714970/125906795-ca622851-17dd-4e00-84b1-bc1425a86a0d.png)

Ws handig voor jou om te weten; hoe weet je nou of een dier bij een GG zit of bij een vrouwenopvang? Op de beginpagina staat achter elk dier dat in de vrouwenopvang verblijft, tussen haakjes de vrouwenopvang genoemd: OH wormerveer, satelietwoning ADAM, Kadera, Moviera, OH Almere, OH Alkmaar, OH Adam etc.). En er is natuurlijk geen koppeling met een GG én het vinkje 'updates' staat niet aangevinkt. 

Zou je dit nog kunnen veranderen? Dat het alleen paars kleurt bij dieren waar het vinkje is aangezet?

Dankjewel!

**Comment by RenildeMendoo** [comment]
En ook hoeven de dieren die bij de vrouwenopvang verblijven, niet de melding 'twee maandelijkse contact verblijf' te krijgen. Hopelijk is het zo duidelijk?

**Comment by sjerpbouwtsites** [comment]
Dit wordt verder afgehandeld in de respectieve issues.
