### ISSUE TITLE
Punt 3: Update eigenaar distribueren naar zijn/haar dieren

### ISSUE THREAD

**Issue by sjerpbouwtsites** [sjerpbouwtsites/blijfvanmijndier#50]
Afkomstig uit https://github.com/sjerpbouwtsites/blijfvanmijndier/issues/38 naar eigen issue.

Punt 3: Update eigenaar distribueren naar zijn/haar dieren
Is het mogelijk om de update van een eigenaar te distrubueren naar zijn/haar dieren? 
Dus bij eigenaar Pascal (eigenaar van Guus en Gert); dat je die update direct kan koppelen aan Guus & Gert? 
Of hadden we t hier juist over gehad, dat dat eigenlijk te moeilijk is?

![image](https://user-images.githubusercontent.com/86714970/124780464-e94e7200-df42-11eb-9262-667f53a7875a.png)

_Originally posted by @RenildeMendoo in https://github.com/sjerpbouwtsites/blijfvanmijndier/issues/38#issuecomment-875667433_

**Comment by sjerpbouwtsites** [comment]
@RenildeMendoo ja dat kan en ja, hier hebben we het over gehad. Ik stelde dit voor, op dat moment zei je het nog niet nodig te hebben... ik dacht dat gaat de volgende stap zijn :p maar ik maak er wel even een aparte kwestie van. Dan kan de rest straks in productie.

**Comment by sjerpbouwtsites** [comment]
> 
> 
> Yes helemaal goed!
> En dan zou hierbij dus ook de optie moeten komen om de update van een GG te dupliceren naar de dieren die bij hem/haar worden opgevangen.

Dat is dan toch een andere functionaliteit. We hebben het hier over eigenaren, niet over gastgezinnen.

**Comment by sjerpbouwtsites** [comment]
Ik ga deze volgende week oppakken, heb ik even een dag focus voor nodig.

**Comment by RenildeMendoo** [comment]
Oh wacht, dit hoefde niet :p want deze stond al genoemd in open issues.
