### ISSUE TITLE
gastgezinnen adressen kopieeren

### ISSUE THREAD

**Issue by sjerpbouwtsites** [sjerpbouwtsites/blijfvanmijndier#51]
Maar hij staat er nu wel op toch? Ik ga gewoon lekker comments schrijven. Ten eerste natuurlijk: super veeeet! Dankjewel!

Punt 1: Wat super handig dat we nu direct iets kunnen kopieëren met een knopje. Zou je dat knopje ook kunnen maken voor het adres kopieëren? Dat zou echt ideaal zijn!

_Originally posted by @RenildeMendoo in https://github.com/sjerpbouwtsites/blijfvanmijndier/issues/36#issuecomment-875670270_

**Comment by sjerpbouwtsites** [comment]
Ja ja, zeker dat kan, maar wat bedoel je met adres?
straat + huisnummer
straat + huisnummer + stad
staat + huisnummer + postcode + stad
of die alle 3 of 4 apart 😋

**Comment by RenildeMendoo** [comment]
Straat + huisnummer + postcode + stad, de hele mikmak ;)
Maar dus alleen deze optie. Dus dat direct het hele adres is gekopieerd met één knopje.

**Comment by sjerpbouwtsites** [comment]
![afbeelding](https://user-images.githubusercontent.com/34159539/133376525-d2507c8f-e86a-4419-b61f-73277e03d5ff.png)

Ik heb 'm meteen er even bijgezet bij alle andere adressen. Staat op staging.

**Comment by sjerpbouwtsites** [comment]
https://github.com/sjerpbouwtsites/blijfvanmijndier/pull/77

**Comment by sjerpbouwtsites** [comment]
@RenildeMendoo ivm de eindigheid van mijn betrekking heb ik de dingen die klaar stonden live gezet, niettegenstaande dat het nog niet helemaal geaccordeerd was. Anders ging dit mogelijk lang op de plank moeten liggen.

**Comment by RenildeMendoo** [comment]
Yes, snap ik! Ik ga nu even je berichtjes bij langs om te kijken hoe & wat. 
Dit kopiëren werkt, yes!

**Comment by RenildeMendoo** [comment]
Oehh super fijn dat het ook bij de andere adressen, chique!
