### ISSUE TITLE
'afmelden' gg

### ISSUE THREAD

**Issue by sjerpbouwtsites** [sjerpbouwtsites/blijfvanmijndier#52]
Punt 2: is het ook mogelijk om een GG helemaal af te melden? Of kan dat alleen door in te vullen dat een gastgezin tot, zeg, 2050 niet beschikbaar is?

_Originally posted by @RenildeMendoo in https://github.com/sjerpbouwtsites/blijfvanmijndier/issues/36#issuecomment-875672179_

Wat bedoel je met afmelden @RenildeMendoo? Is dat
1. het verwijderen van een gastgezin
2. het in zijn algemeenheid onbeschikbaar maken van een gastgezin

**Comment by RenildeMendoo** [comment]
Het gaat om het verwijderen van een GG (maar dat die nog wel 'ergens' in ons systeem blijft hangen). Dus een GG die bij ons aangeeft; ik wil nooit meer dieren opvangen en ik wil ook niet meer benaderd worden. Met het nieuwe systeem wat jij straks live gaat zetten, zou ik dat doen door een GG op onbeschikbaar te zetten tot 3000, maar mooier is natuurlijk als je het GG kan afmelden.

**Comment by sjerpbouwtsites** [comment]
Deze pak ik nu op.

**Comment by sjerpbouwtsites** [comment]
Ik veronderstel dat een afgemelde GG
1. niet meer onderdeel is van het overzicht
2. niet meer gekoppeld kan worden
3. niet automatisch ontkoppeld, indien deregistreren en nog gekoppelt dan genereert het fouten
4. louter in een apart overzicht te zien zijn onder http://localhost:8000/guests/deregistered

**Comment by RenildeMendoo** [comment]
Wat ga je hard zeg! Nu al met prio 3 bezig, goed bezig!
Je veronderstellingen kloppen! Ik krijg alleen een foutmelding als ik op je linkje klik:
![image](https://user-images.githubusercontent.com/86714970/130814669-8930107b-c50c-44d0-85ce-b2e365e59777.png)

**Comment by sjerpbouwtsites** [comment]
![afbeelding](https://user-images.githubusercontent.com/34159539/132451136-da5355af-35b4-42d6-8212-cef1138c52a6.png)

**Comment by sjerpbouwtsites** [comment]
![afbeelding](https://user-images.githubusercontent.com/34159539/132451179-cd712dbc-cd9c-4565-a448-fd3224251596.png)

**Comment by sjerpbouwtsites** [comment]
yes het staat op staging @RenildeMendoo

**Comment by RenildeMendoo** [comment]
Ziet er goed uit!

**Comment by RenildeMendoo** [comment]
Deze doet het ook goed nu ie live staat!
