### ISSUE TITLE
laatste update eigenaar in sidemenu

### ISSUE THREAD

**Issue by sjerpbouwtsites** [sjerpbouwtsites/blijfvanmijndier#54]
Maar vanuit het team hebben we nog een vraag:

•	In het overzicht van eigenaar kan je nu niet zien dat er een update geplaatst is bij de eigenaar. Bij GG en dieren zie je dan rechtsonder altijd de eerste twee zinnen van de laatste update/laatste twee updates Zou dat hier ook kunnen? 

Zo is het nu bij eigenaar: 
![image](https://user-images.githubusercontent.com/86714970/125444724-2756131b-8c60-4aca-ad2f-a56093e8d020.png)

En zo is het bij GG: 
![image](https://user-images.githubusercontent.com/86714970/125444973-e9a9a4e4-20fe-4f1a-bcfd-2a5c6eb9142c.png)

_Originally posted by @RenildeMendoo in https://github.com/sjerpbouwtsites/blijfvanmijndier/issues/37#issuecomment-879011428_

**Comment by sjerpbouwtsites** [comment]
Staat op staging.

**Comment by RenildeMendoo** [comment]
Ziet er goed uit :D
