### ISSUE TITLE
BUGS na live gang Maya 

### ISSUE THREAD

**Issue by RenildeMendoo** [sjerpbouwtsites/blijfvanmijndier#55]
Hi Sjerp,

Vandaag ben ik aan het werk en ik zal even in dit onderwerp de bugs zetten die ik tegen kom. 

De eerste:
Een dier koppelen aan een GG (die had ik al in een andere opmerking gezet); dit werkt niet meer.

**Comment by RenildeMendoo** [comment]
De tweede:
Ik kan  het pension Markenvelde niet meer aanpassen. 

![image](https://user-images.githubusercontent.com/86714970/125922011-bcffa0c4-8a22-4c59-9a20-b676de05a3de.png)

Als ik op 'wijzigen' klik krijg deze foutmelding:

![image](https://user-images.githubusercontent.com/86714970/125921953-896be3ec-5c76-4bbd-a639-bac317f7561c.png)

**Comment by sjerpbouwtsites** [comment]
@RenildeMendoo Dat is wel bagger zeg. Ik ga er naar kijken.

**Comment by sjerpbouwtsites** [comment]
@RenildeMendoo Het zou nu verholpen moeten zijn

**Comment by RenildeMendoo** [comment]
Niet een echt totale bug, maar wel opvallend:
Ik kan nu aanvinken dat een GG een eigen dier heeft, maar dat zie ik niet terug in de overzichtspagina van het GG:

![image](https://user-images.githubusercontent.com/86714970/125948356-0d0a854e-9959-4799-8fc2-795e2e1dc035.png)

**Comment by RenildeMendoo** [comment]
> @RenildeMendoo Het zou nu verholpen moeten zijn

Yes, het werkt! dankjewel!

**Comment by sjerpbouwtsites** [comment]
@RenildeMendoo  de match bug zou nu ook verholpen moeten zijn.

**Comment by RenildeMendoo** [comment]
@sjerpbouwtsites We hebben nog een probleem; heel veel adressen van eigenaren staan nu in Den Bosch, terwijl die eigenaren daar niet wonen. Heb jij nog de oude data set van adressen? Zou je die kunnen aanpassen?
Het belangrijkste is dat nu eerst bij de dieren in project de eigenaren weer het goede adres krijgen. Alumni dier-eigenaren adressen zijn wat minder belangrijk.

**Comment by RenildeMendoo** [comment]
> @RenildeMendoo de match bug zou nu ook verholpen moeten zijn.

Yes het werkt :D Dankjewel!

**Comment by RenildeMendoo** [comment]
En nog eentje gevonden: bestanden die we hebben geüpload, kunnen we niet meer openen:
Bij een dier (bijv Max of Yrrah of Malik) staat een bestand:

![image](https://user-images.githubusercontent.com/86714970/126490788-7f9f0799-91c4-4bc1-b519-b9c1165113e8.png)

En dan krijg ik deze melding:
![image](https://user-images.githubusercontent.com/86714970/126490812-8420c7d6-c6ac-4c69-a89c-160df3e242da.png)

**Comment by sjerpbouwtsites** [comment]
ik sluit deze issue omdat alles in verdere issues wordt afgehandeld.
