### ISSUE TITLE
GG kan eigen dier hebben maar is niet terug te zien in single view

### ISSUE THREAD

**Issue by sjerpbouwtsites** [sjerpbouwtsites/blijfvanmijndier#56]
Niet een echt totale bug, maar wel opvallend:
Ik kan nu aanvinken dat een GG een eigen dier heeft, 
![image](https://user-images.githubusercontent.com/86714970/125948479-c7e6c00f-41dc-4047-b978-e088f772ec9c.png)

maar dat zie ik niet terug in de overzichtspagina van het GG:

![image](https://user-images.githubusercontent.com/86714970/125948356-0d0a854e-9959-4799-8fc2-795e2e1dc035.png)

_Originally posted by @RenildeMendoo in https://github.com/sjerpbouwtsites/blijfvanmijndier/issues/55#issuecomment-881414368_

**Comment by sjerpbouwtsites** [comment]
duidelijk

**Comment by sjerpbouwtsites** [comment]
![afbeelding](https://user-images.githubusercontent.com/34159539/130776442-09bc9609-288c-4ee8-884f-613a7dabcef1.png)
zet ik naar staging

**Comment by RenildeMendoo** [comment]
Top! 
Ik zie wel dat er nu weer een dubbele rij diersoorten staat bij 'eigen dier':

![image](https://user-images.githubusercontent.com/86714970/130808939-af385db3-df71-495f-92bb-5944bb746ee0.png)
