### ISSUE TITLE
adressen dieren in den bosch beland

### ISSUE THREAD

**Issue by sjerpbouwtsites** [sjerpbouwtsites/blijfvanmijndier#57]
@sjerpbouwtsites We hebben nog een probleem; heel veel adressen van eigenaren staan nu in Den Bosch, terwijl die eigenaren daar niet wonen. Heb jij nog de oude data set van adressen? Zou je die kunnen aanpassen?
Het belangrijkste is dat nu eerst bij de dieren in project de eigenaren weer het goede adres krijgen. Alumni dier-eigenaren adressen zijn wat minder belangrijk.

_Originally posted by @RenildeMendoo in https://github.com/sjerpbouwtsites/blijfvanmijndier/issues/55#issuecomment-883404443_

**Comment by sjerpbouwtsites** [comment]
@RenildeMendoo Dit pak ik nu op.

**Comment by sjerpbouwtsites** [comment]
Dit probleem zit niet in de database maar in de code.

**Comment by sjerpbouwtsites** [comment]
Dit probleem ga ik vandaag niet af kunnen handelen. Maar ik heb 'm gespot.

**Comment by RenildeMendoo** [comment]
Dankjewel! :)

**Comment by sjerpbouwtsites** [comment]
```
ALTER TABLE `owners` ADD address_id TEXT default NULL;
UPDATE `owners` SET address_id = SHA2(CONCAT(street, house_number, postal_code), 256);
```
Dit is de reden. De testdatabase die ik had gekregen had adressen. Jullie werkende database had bij de eigenaren vaak geen adres. Dat wist ik niet. Dus bovenstaande code geeft ze allemaal exact dezelfde address_id.

**Comment by sjerpbouwtsites** [comment]
ok. heb er wat op bedacht

**Comment by RenildeMendoo** [comment]
Goed bezig! Even voor de zekerheid; je bent er nu nog mee bezig, of niet? Want er staan nog steeds wel flink wat adressen op hetzelfde adres (dat is nu van Reigersbergenstraat in Amsterdam, dat moet vast gezellig zijn daar ;))

**Comment by sjerpbouwtsites** [comment]
Dus ik heb het opgelost, in die zin, dat nu de adressen weer los van elkaar op te slaan zijn. Want ieder van die adressen overschreef al de anderen in die serie, want ze hadden dezelfde ID. Betekent wel dat specifiek deze adressen opnieuw ingevoerd moeten worden. Je herkent ze aan de termen 'onzin onzin onzin'.

**Comment by RenildeMendoo** [comment]
Fijn dat het nu opgelost is! Heb jij toevallig nog ergens een lijst met adressen van eigenaren, van voor de update? Misschien kunnen we die dan toch ergens nog opslaan (niet op Maya, maar ergens anders) zodat we toch nog wel adressen kunnen opzoeken.

**Comment by RenildeMendoo** [comment]
En zou je de 'onzin onzin onzin' kunnen vervangen door 'onbekend'? Dat staat wat mooier ;)
