### ISSUE TITLE
bestanden die we hebben geüpload, kunnen we niet meer openen:

### ISSUE THREAD

**Issue by sjerpbouwtsites** [sjerpbouwtsites/blijfvanmijndier#58]
En nog eentje gevonden: bestanden die we hebben geüpload, kunnen we niet meer openen:
Bij een dier (bijv Max of Yrrah of Malik) staat een bestand:

![image](https://user-images.githubusercontent.com/86714970/126490788-7f9f0799-91c4-4bc1-b519-b9c1165113e8.png)

En dan krijg ik deze melding:
![image](https://user-images.githubusercontent.com/86714970/126490812-8420c7d6-c6ac-4c69-a89c-160df3e242da.png)

_Originally posted by @RenildeMendoo in https://github.com/sjerpbouwtsites/blijfvanmijndier/issues/55#issuecomment-884162567_

**Comment by sjerpbouwtsites** [comment]
@RenildeMendoo Dit pak ik nu op.

**Comment by sjerpbouwtsites** [comment]
![afbeelding](https://user-images.githubusercontent.com/34159539/127449647-fc835dee-af61-45f9-b087-690a0402e3df.png)

Hier lopen meerdere dingen door elkaar mis. Ik heb voordat ik iets live zette een volledige backup gemaakt van de database en de bestanden. Hier zie je welke documenten er live stonden voordat ik iets live zette. Ik heb geel gemaakt welke pdfs aanwezig waren. Bij max hoort pdf 346. Maar die ontbreekt volledig. Eens kijken of die ergens anders is beland..

**Comment by sjerpbouwtsites** [comment]
Gevonden! Dit was al op 2 juni fout gegaan.

**Comment by sjerpbouwtsites** [comment]
Zoooooo he dit was echt even schrikken zeg
Maar ik had gelukkig backups. Fix @RenildeMendoo

**Comment by RenildeMendoo** [comment]
Yeahhh cooool :D Dankjewel!
