### ISSUE TITLE
Bestanden uploaden op Maya

### ISSUE THREAD

**Issue by RenildeMendoo** [sjerpbouwtsites/blijfvanmijndier#59]
Hi Sjerp,
Vandaag probeerde ik een bestand toe te voegen op Maya, via deze pagina:
![image](https://user-images.githubusercontent.com/86714970/127614160-58d10fd2-aead-40da-bfbe-c82b643a238b.png)

maar dan krijg ik deze melding:

![image](https://user-images.githubusercontent.com/86714970/127614120-f8df3e1d-ef74-4dbb-b658-e37d13017da1.png)

Enig idee waar dit door komt?

**Comment by sjerpbouwtsites** [comment]
He renilde

fijn dat je hier een issue voor heb aangemaakt. 

Ja, ik heb hier een idee van. Het is ontstaan tijdens de update van 2 juni. Bas had de varia referentie waarden voor de tablegroup-tabel per controller op de laravel root controller gezet. Dat hoort absoluut niet. Maar dat is wel hoe de hele app is opgebouwd. Ik heb hiervoor een aparte model aangemaakt: https://github.com/sjerpbouwtsites/blijfvanmijndier/blob/dev/app/Tablegroup.php 
zodat dit wel netjes gedaan kon worden specifiek met methoden zoals `public static  function get_tablegroup_by_type($type = null){}`. Dit heb ik vervolgens door de hele app toegepast voorzover ik weet. Dit is dus één van die hele diepe aanpassingen om op lange termijn de app houdbaar te maken. Documenten uploaden en laden, zo bleek al eerder, had ik echter niet op mijn netvlies. Dus viel daarbij zowel het laden als het inladen door de mand. Wat moet gebeuren is dat in de document controller de nieuwe tablegroup method aangeroepen wordt en dan vermoed ik dat het euvel is opgelost. 

Of wilde je een minder letterlijk antwoord?
Ik ga morgenochtend weer even werken.

**Comment by RenildeMendoo** [comment]
Hahahaha, dankjewel! Ik begin het bijna te begrijpen hoor ;)

**Comment by RenildeMendoo** [comment]
Aaarghhh ik wil deze heropenen, maar ik snap niet hoe dat moet... Het bestanden uploaden lukt dus nog steeds niet. Ik kan wel nu de bestanden die op Maya staan, weer openen (dat kon eerder ook niet). Maar het uploaden van nieuwe bestanden lukt dus niet. Ik krijg deze melding:

![image](https://user-images.githubusercontent.com/86714970/128476680-e1d0db36-64a3-4436-8ead-4234f2f226aa.png)

**Comment by sjerpbouwtsites** [comment]
![afbeelding](https://user-images.githubusercontent.com/34159539/129867020-b7275572-83d6-4d63-bccf-8c7c9bb736a2.png)
Fix en staat op staging.

**Comment by RenildeMendoo** [comment]
Super!
