### ISSUE TITLE
Melding 'update eigenaar' alleen wanneer het vinkje aangevinkt staat

### ISSUE THREAD

**Issue by RenildeMendoo** [sjerpbouwtsites/blijfvanmijndier#61]
Hoi Sjerp,

Deze had ik ergens nog in een ander onderwerp staan, maar voor 't overzicht even een nieuw onderwerp ervan gemaakt met prio 1. 

Ook bij de 'nieuwe' Maya heb ik hierbij nog een opmerking:

Bij elk dier hebben we de optie 'updates' (hiermee bedoelen we 'tweewekelijkse update', dus het bericht wat elke twee weken naar een eigenaar wordt gestuurd). Deze optie kan wordena aangevinkt, maar dat hoeft niet:

![image](https://user-images.githubusercontent.com/86714970/125906311-e2450f30-67c7-4f72-9bd1-ad060a2ffef2.png)

We hebben deze optie van het aanvinken toegevoegd, omdat eigenaren die met hun dier in een vrouwenopvang verblijven, niet elke twee weken een update hoeven te ontvangen. Zij hebben immers het dier bij zich. Deze eigenaren krijgen dus geen vinkje. Terwijl een dier wat bij een GG verblijft, wél dit vinkje krijgen, zodat we elke twee weken een herinnering krijgen dat ze een update over het dier moeten ontvangen. 

Nu zie ik dat op de nieuwe Maya álle dieren een paars vakje (= tijd voor 'update eigenaar' = 2 wekelijkse update) hebben gekregen. Ook dus de dieren waarbij dit vinkje **niet** is aangevinkt. Zoals Coco & Neel (die van de printscreen hierboven) maar ook Arie:

![image](https://user-images.githubusercontent.com/86714970/125906795-ca622851-17dd-4e00-84b1-bc1425a86a0d.png)

Ws handig voor jou om te weten; hoe weet je nou of een dier bij een GG zit of bij een vrouwenopvang? Op de beginpagina staat achter elk dier dat in de vrouwenopvang verblijft, tussen haakjes de vrouwenopvang genoemd: OH wormerveer, satelietwoning ADAM, Kadera, Moviera, OH Almere, OH Alkmaar, OH Adam etc.). En er is natuurlijk geen koppeling met een GG én het vinkje 'updates' staat niet aangevinkt. 

Zou je dit nog kunnen veranderen? Dat het alleen paars kleurt bij dieren waar het vinkje is aangezet?

Dankjewel!

_Originally posted by @RenildeMendoo in https://github.com/sjerpbouwtsites/blijfvanmijndier/issues/39#issuecomment-881229089_

**Comment by RenildeMendoo** [comment]
En ook hoeven de dieren die bij de vrouwenopvang verblijven, niet de melding 'twee maandelijkse contact verblijf' te krijgen. Hopelijk is het zo duidelijk?

_Originally posted by @RenildeMendoo in https://github.com/sjerpbouwtsites/blijfvanmijndier/issues/39#issuecomment-883410040_

**Comment by sjerpbouwtsites** [comment]
Hoi Renilde,

wat een labyrint is dit dan. In het Engels is hier een goed woord voor: byzantine. In de IT gebruiken we de term spaghetti. Het is de verplichting van iedere programmeur om te voorkomen labyrinten aan te leggen. Ze zijn foutgevoelig en slecht te onderhouden. En dat is dus precies wat hier gebeurd - iemand heeft dit ooit aangelegd maar het is niet te volgen voor mij mede omdat ik dingen niet gehoord heb. Voor mijn opvolger wordt dat nog veel erger, want het is nog complexer gemaakt. Eén van de voornaamste problemen hier is dat de term updates allemaal verschillende dingen betekenen in verschillende conteksten maar dat het niet uit die contekst valt op te maken wat updates betekent of betekenen. Ik raak behoorlijk in de war over wat nu precies de bedoeling is of gevraagd wordt. 

Dus even ter herhaling en om het voor mij op een rijtje te zetten, de afgesproken functionaliteit was dat er 'updates' zijn, en dat indien er een bepaalde termijn was verstreken, er een notificatie zou komen op de overzichts~ en de detailpagina.
Je eerste verzoek is dat hier een uitzondering op komt wat de 'eigenaarsupdate' heet. Nu moet ik even opzoeken wat dat ook al weer mogelijk kan betekenen, want daar zijn er geloof ik 2 van. Ok dat kan ik nu niet vinden, maar in mijn logica zie ik in ieder geval 'owner update' dus ik neem even aan dat dat is waar je het over hebt met de eigenaars update. Ok. 

Om de verwarring compleet te maken blijk ik een vooruitziende blik te hebben gehad, verwacht dat je me zoiets zou gaan vragen, en hier rekening mee te gehouden te hebben in mijn logica. Er is een 'heeft eigenaars update nodig' eigenschap en die valt dus te ontkennen door te zoeken naar het aangevinkt zijn van de 'updates' eigenschap op het dier. Ok. Tot zo ver goed denk ik. Dat kan ik bouwen. Doe ik nu, daarna kijk ik naar die verwarring rondom opvangsoorten.

**Comment by sjerpbouwtsites** [comment]
Ik ben momenteel de bijbel weer eens aan het bestuderen ik vind dat logischer in elkaar zitten dan 'updates' 😂⛪

**Comment by sjerpbouwtsites** [comment]
Ok ik snap nu denk ik je tweede vraag... die is geen vraag maar een mededeling. Ok. Dus daar hoef ik niets mee. Dus dan zet ik dit even naar staging. 

Dit is iets wat echt anders gearchitectuurt moet worden. Dieren zijn simpelweg of bij hun eigenaar of niet, daar volgt alles uit. Dat is de logica. Dat is wat opgeslagen moet worden, niet een afgeleide eigenschap zoals 'updates'.

**Comment by sjerpbouwtsites** [comment]
Nee! Heb nog deze opmerking gevonden: 

> En ook hoeven de dieren die bij de vrouwenopvang verblijven, niet de melding 'twee maandelijkse contact verblijf' te krijgen. Hopelijk is het zo duidelijk?

**Comment by sjerpbouwtsites** [comment]
Dus de tweede vraag waar ik het over had, die impliciet was uit je tekst, bleek uit een verdere opmerking in die originele issue waar dit vandaan kwam. Dat is wel echt een problematisch verzoek. Want dan moet ik dus uit de naam van een dier gaan afleiden dat een dier bij de eigenaar in een opvang is. En ik zie nu al dat dat op minstens 3 manieren geschreven wordt. HmmHmmHmm. Het probleem is niet dat ik er niet wat voor kan schrijven. Het probleem is: wil ik mijn opvolger met een labyrint opzadelen. Hmmm

**Comment by RenildeMendoo** [comment]
Haha, ik ben het helemaal met je eens; de term 'update' gebruiken we echt veeeel te veeeel. En dan weet je nog niet eens waar we 't allemaal op de andere plek óók nog voor gebruiken XD Ik ben al wel bezig om dat langzaamaan te veranderen naar andere namen, zodat we dus niet telkens weer die verwarring krijgen XD

**Comment by RenildeMendoo** [comment]
> Dus de tweede vraag waar ik het over had, die impliciet was uit je tekst, bleek uit een verdere opmerking in die originele issue waar dit vandaan kwam. Dat is wel echt een problematisch verzoek. Want dan moet ik dus uit de naam van een dier gaan afleiden dat een dier bij de eigenaar in een opvang is. En ik zie nu al dat dat op minstens 3 manieren geschreven wordt. Daarnaast is het gewoon superslecht om zo met data om te gaan. HmmHmmHmm. Het probleem is niet dat ik er niet wat voor kan schrijven. Koffie kan, thee kan, etc. Het probleem is: wil ik mijn opvolger met een labyrint opzadelen. Hmmm
> 
> toevoeging:
> Ok, ik heb er over nagedacht. Dit is een te problematisch verzoek. Hiervoor moet dus die optie 'is bij eigenaar' ingevoerd worden.

Nou durf ik natuurlijk nooit iets te zeggen over de mate van problematische verzoeken, omdat ik er natuurlijk lang niet genoeg van snap... ;) Maar ik ga het nu toch doen:

Zou dit niet te koppelen zijn aan of het dier gekoppeld is aan een gastgezin of aan pension? 

Bijvoorbeeld Amy: Amy verblijft bij een gastgezin. En daarom is deze hond netjes gekoppeld aan het gastgezin (en is het vinkje 'updates' aangevinkt). Deze koppeling aan het gastgezin zet vervolgens de melding 'gastgezin/pension update' aan. 
Bella (OH Adam): Bella verblijft bij de eigenaar in de opvang. Dat weet het systeem omdat Bella niet is gekoppeld aan een gastgezin of aan pension (en ook is het vinkje 'updates' niet aangevinkt en staat er achter haar naam 'OH Adam'). Omdat de koppeling ontbreekt, komt er bij Bella geen melding 'gastgezin/pension update'.

Of is dit te simpel gedacht van mij?

**Comment by sjerpbouwtsites** [comment]
Als 1. niet gekoppeld aan shelter of guest en 2. 'updates' is uitgevinkt bij het dier, DAN geen eigenaar update.

tekstje erbij zetten bij 'updates' bij dieren die dit uitlegt. Dat het met de hand moet. En dat de koppeling relevant is. Bij de koppeling zet ik het ook.

**Comment by sjerpbouwtsites** [comment]
Ok. Maar met deze info kan ik ook een extra cue er bij bouwen. Locatie van een dier is eigenlijk vrij primaire info zelfs. 
Dus bij deze staat er een roze hartje bij indien eigenaar en dier samen zijn ❤
![afbeelding](https://user-images.githubusercontent.com/34159539/132458107-6955080f-157b-4478-bc2d-416c954ddbe4.png)

**Comment by sjerpbouwtsites** [comment]
@RenildeMendoo staat weer op staging

**Comment by sjerpbouwtsites** [comment]
Ik heb nooit eerder een roze lintje ergens op geprogrammeerd. Voor alles is een eerste keer.

**Comment by RenildeMendoo** [comment]
Ooooh dit klinkt echt geniaal! Maar... op de staging zie ik dit nog.
- De kleurtjes ontbreken
- De foto's van de dieren staan scheef
- Er staan alleen zwarte hartjes
![image](https://user-images.githubusercontent.com/86714970/132499434-db36033e-12bd-404f-87c9-18f71cc6d23e.png)

**Comment by RenildeMendoo** [comment]
De kleurtjes en foto's zijn nu wel goed!
Maar het roze hartje staat nog niet goed genoteerd bij de dieren die daadwerkelijk bij de eigenaar verblijven. Zo is hond Amy gekoppeld aan een gastgezin, terwijl kat Bella (OH Adam) niet gekoppeld is aan een GG of pension:

![image](https://user-images.githubusercontent.com/86714970/132855476-db150d3f-a276-441e-bfb2-2e87faa136c1.png)

**Comment by sjerpbouwtsites** [comment]
> 
> 
> Ooooh dit klinkt echt geniaal! Maar... op de staging zie ik dit nog.
> 
>     * De kleurtjes ontbreken
> 
>     * De foto's van de dieren staan scheef
> 
>     * Er staan alleen zwarte hartjes
> 
>     * Geen enkel dier heeft meer de melding 'tweewekelijkse update voor eigenaar'. Dus ook niet de dieren die bij GG zitten en waarvan de eigenaar weer een update nodig heeft. Klopt dat?
>       ![image](https://user-images.githubusercontent.com/86714970/132499434-db36033e-12bd-404f-87c9-18f71cc6d23e.png)

Dat zit 'm dus in een of andere caching. Zowel mogelijk in de browser die je gebruikt als mogelijk iets op de server. Daar maak ik ook rare dingen in mee... zie mn migratie gids 🤡

**Comment by sjerpbouwtsites** [comment]
Dit wordt nu op staging gezet. Inderdaad er was een foutje, ook nog een andere zag ik net. Dan vermoed ik dat dit nu afgehandeld is. (vergeet niet je browsercache te legen)

https://github.com/sjerpbouwtsites/blijfvanmijndier/pull/76

**Comment by RenildeMendoo** [comment]
Yes helemaal goed zo  :) Fijn!
Nog één kleine vraag, ik zag de tekst 'duiding van 'updates'' onderaan een dierpagina staan, wat betekent dat? 

![image](https://user-images.githubusercontent.com/86714970/136008457-d7d93b6e-25e7-44cf-b19b-5f645df7e9c5.png)

En nog een tweede: bij elk dier staat nu 'Ja' bij updates, ook als het vinkje niet is aangevinkt. Bijvoorbeeld hond Chrissy.

**Comment by RenildeMendoo** [comment]
Er zijn een paar dieren (Bailey, Indy, Kizzy, Mauw) die wel een roze hartje hebben, maar niet bij de eigenaar verblijven. Waar zit daar de fout?
