### ISSUE TITLE
Kleine lay-out dingen 

### ISSUE THREAD

**Issue by RenildeMendoo** [sjerpbouwtsites/blijfvanmijndier#62]
Ook mijn collega's vinden het super netjes er uit zien. Echt zooo vet :D 

Onze opmerkingen:
1) Kan je voor de kleurcodes 'onze' Mendoo-kleuren gebruiken? Ik heb de kleurcodes net doorgestuurd. 
2) Kan je op Maya het logo van Mendoo zetten? Ipv het logo van BvmD wat er nu nog staat. Oké, ik besef me dat dit officieel niet bij hoort bij dit onderwerp, ik hoop dat je het me kan vergeven ;)
3) Kan je bij onderstaande teksten het tekstje 'Verblijf vervolg contact' veranderen naar 'verblijf gastgezin/pension vervolg contact'? Dat lijkt ons wat duidelijker werken:
![image](https://user-images.githubusercontent.com/86714970/125444391-eac22733-3190-4e4d-a40a-f8de2466bf61.png)

4) Kan je het 'peace'-handje (dat er te zien is als alles oké is) groen maken? Dan is het wat opvallender
5) Kan je het lettertype van de diernamen (en alle lettertypes) hetzelfde maken als het lettertype wat op de 'echte' Maya wordt gebruikt?

_Originally posted by @RenildeMendoo in https://github.com/sjerpbouwtsites/blijfvanmijndier/issues/39#issuecomment-879008691_

**Comment by sjerpbouwtsites** [comment]
@RenildeMendoo jaja... en toen had ik de opdracht 1. te ruim geinterpreteerd. Ik heb de stijlgids doorgevoerd. Dus ook de lettertypen genomen. Nou, ziet er wel wat beter uit eigenlijk.

**Comment by sjerpbouwtsites** [comment]
staat op staging

**Comment by RenildeMendoo** [comment]
Wauw, ziet er heel mooi uit!

Maar nu zijn hier alle kleuren verdwenen?
![image](https://user-images.githubusercontent.com/86714970/129875372-67a6d99e-6a78-44c1-b5f9-e73366e77581.png)
Dat is ook jammer... of had je dat express gedaan? 

Ook missen nog punt 3 en 4 uit het comment hierboven, of kijk ik er over heen?

**Comment by sjerpbouwtsites** [comment]
Ja klopt dat heb ik express gedaan. Zo is het consistent Mendoo kleuren. 
En punt 3 en 4 heb ik zeker opgepakt

**Comment by sjerpbouwtsites** [comment]
![afbeelding](https://user-images.githubusercontent.com/34159539/130764125-2f979708-defe-4c8b-b4e1-3422edad7062.png)
Zie hier bv het groene handje. Er is alleen geen groen in de mendoo kleurenset.

**Comment by RenildeMendoo** [comment]
Yeahhh cool, ik zie het idd! :D 
Netjes!

En er zijn dus te weinig 'mendoo' kleuren om elk type een eigen kleur te geven? Of begrijp ik het verkeerd? 
Dus bijv 'eigenaar update vervolg' paars, 'hulpverlener update' rood, 'gastgezin/pension update' oranje, 'jaarevaluatie' zwart? 
Dan kom ik wel mooi uit met de aantal soorten updates, of ben ik dan weer helemaal in de war :p Dat kan ook hoor!
