### ISSUE TITLE
Tekstuele aanpassingen 

### ISSUE THREAD

**Issue by RenildeMendoo** [sjerpbouwtsites/blijfvanmijndier#70]
Hoihoi,

En ik had ergens op github nog een paar kleine tekstuele veranderingen gezet, maar die kan ik nergens meer terug vinden. Dus vandaar hier nog even opnieuw. Ik maak even een comment per tabblad waar we de wijzigingen willen hebben. Voor het overzicht (hoop ik ;) )

**Comment by RenildeMendoo** [comment]
Punt 1: Tabblad dieren

Onder het tabblad dieren zijn nu vier kopjes:  'Alle dieren' 'Dieren todo' 'Nieuw dier' en 'Alumni'. 
Kan dit aangepast worden naar: 'Dieren in project', 'Dieren to do', 'Nieuw dier' en 'Dieren uit project'?

**Comment by RenildeMendoo** [comment]
Punt 2: Tabblad gastgezinnen

Onder het tabblad gastgezinnen zijn nu 'Alle GG', 'Beschikbare GG', 'Onbeschikbare GG', 'Nieuwe GG'
Kan dit aangepast worden naar: 'Alle GG', 'Beschikbare GG', 'Niet beschikbare GG' en 'Nieuw GG'?

**Comment by RenildeMendoo** [comment]
Punt 3: het vele gebruik van het woord 'updates' 

Wat je ook al noemde in een ander Issue. Waar ik het dus 100% mee eens ben en af en toe ook helemaal gek van word.
Ik zie dat je op de beginpagina 'Dier' daar het woord 'update' regelmatig hebt weggehaald (super fijn):
![image](https://user-images.githubusercontent.com/86714970/130818499-a9597afd-c4ed-4a09-880b-1fadcc8ac041.png)

Maar als ik met m'n muis op een icoontje ga staan, komt er nog steeds 'eigenaar update vervolg' te staan (of bijv hulpverlener update). Zou het beter zijn om daar ook het woord 'update' steeds weg te halen? Of maakt dat weinig uit en moeten wij in het team gewoon afleren om het woord 'update' overal maar voor te gebruiken?

**Comment by sjerpbouwtsites** [comment]
> 
> 
> Punt 2: Tabblad gastgezinnen
> 
> Onder het tabblad gastgezinnen zijn nu 'Alle GG', 'Beschikbare GG', 'Onbeschikbare GG', 'Nieuwe GG'
> Kan dit aangepast worden naar: 'Alle GG', 'Beschikbare GG', 'Niet beschikbare GG' en 'Nieuw GG'?

Nee dit kan helaas niet. Want er is net een nieuw tabblad bijgekomen dus het wringt nu... zie de issue https://github.com/sjerpbouwtsites/blijfvanmijndier/issues/52

**Comment by sjerpbouwtsites** [comment]
> 
> 
> Punt 1: Tabblad dieren
> 
> Onder het tabblad dieren zijn nu vier kopjes: 'Alle dieren' 'Dieren todo' 'Nieuw dier' en 'Alumni'.
> Kan dit aangepast worden naar: 'Dieren in project', 'Dieren to do', 'Nieuw dier' en 'Dieren uit project'?

Gedaan, staat straks op staging

**Comment by sjerpbouwtsites** [comment]
> 
> 
> Punt 3: het vele gebruik van het woord 'updates'
> 
> Wat je ook al noemde in een ander Issue. Waar ik het dus 100% mee eens ben en af en toe ook helemaal gek van word.
> Ik zie dat je op de beginpagina 'Dier' daar het woord 'update' regelmatig hebt weggehaald (super fijn):
> ![image](https://user-images.githubusercontent.com/86714970/130818499-a9597afd-c4ed-4a09-880b-1fadcc8ac041.png)
> 
> Maar als ik met m'n muis op een icoontje ga staan, komt er nog steeds 'eigenaar update vervolg' te staan (of bijv hulpverlener update). Zou het beter zijn om daar ook het woord 'update' steeds weg te halen? Of maakt dat weinig uit en moeten wij in het team gewoon afleren om het woord 'update' overal maar voor te gebruiken?

eh, nou, bijvoorbeeld in deze zin dus: 
_EIGENAAR UPDATE. Dit dier is langer dan twee weken in het project, maar er is geen eigenaar update._
Hier gebruik ik het dus ook door elkaar. In de eerste geval is het letterlijk een update, in het tweede geval is het een bericht, of notitie, iets dergelijks. Dan moet ik dus een andere zelfstandig naamwoord hebben. Uhm. Maar daarvoor snap ik het niet goed genoeg!!!

Weet je wat: leef je uit met deze zinnen.
```php
			if (!$uc['has_owner_update']) {
				 $icons[] = Animal::make_icon_row(["female"], 'EIGENAAR UPDATE. Dit dier is langer dan twee weken in het project, maar er is geen eigenaar update.');
				$prompts[] =  "Eigenaar eerste contact.";
			} else if(!$uc['owner_update_on_time']) {
				$icons[] = Animal::make_icon_row(['repeat',"female"], 'EIGENAAR UPDATE VERVOLG. Er was eerder contact met de eigenaar, maar dat is langer dan twee weken geleden.');
				$prompts[] = "Eigenaar vervolg contact.";
			}
		endif; // needs owner update

		if ($uc['needs_caregiver_update']) :
			if (!$uc['has_caregiver_update'] || !$uc['caregiver_update_on_time']){
				$uc['in_todo_list'] = true;
			}
			if (!$uc['has_caregiver_update']) {
				$icons[] = Animal::make_icon_row(["users"], 'HULPVERLENER UPDATE. Dit dier is langer dan twee maanden in het project, maar de hulpverlening is nog niet gesproken.');
				$prompts[] = "Hulpverlening eerste contact.";
			} else if(!$uc['caregiver_update_on_time']) {
				$icons[] = Animal::make_icon_row(['repeat',"users"], 'HULPVERLENER UPDATE. Er was eerder contact met de hulpverlening, maar dat is langer dan twee maanden geleden.');
				$prompts[] = "Hulpverlening vervolg contact.";		
			}
		endif; // needs caregiver update
		
		if ($uc['needs_pension_guest_update']) :
			if (!$uc['has_pension_guest_update'] || !$uc['pension_guest_update_on_time']){
				$uc['in_todo_list'] = true;
			}
			if (!$uc['has_pension_guest_update']) {
				$icons[] = Animal::make_icon_row(["home"], 'GASTGEZIN/PENSION UPDATE. Dit dier is langer dan twee maanden in het project, maar het verblijf is nog niet gesproken.');
				$prompts[] = "Verblijf eerste contact.";
			} else if(!$uc['pension_guest_update_on_time']) {
				$icons[] = Animal::make_icon_row(['repeat',"home"], 'GASTGEZIN/PENSION UPDATE. Er was eerder contact met het verblijf, maar dat is langer dan twee maanden geleden.');
				$prompts[] = "verblijf gastgezin/pension vervolg contact.";		
			}
		endif; // needs pension guest update

		if ($uc['needs_jaarevaluatie_update']) :
			if (!$uc['has_jaarevaluatie_update']){
				$uc['in_todo_list'] = true;
			}
			if (!$uc['has_jaarevaluatie_update']) {
				$icons[] = Animal::make_icon_row(["sign-out"], 'JAAREVALUATIE UPDATE. Dit dier is langer dan tien maanden in het project, het wordt tijd voor een evaluatiegesprek.');
				$prompts[] = "Jaarevaluatie nodig.";
			} 
		endif; // needs jaarevaluatie update
```

**Comment by sjerpbouwtsites** [comment]
> 
> 
> Punt 4: kleine letter ipv hoofdletter (omg ik durf deze bijna niet te schrijven ;) )
> 
> Je hebt hier alle mogelijkheden met een hoofdletter, behalve 'verblijf gastgezin/pension vervolg contact'. Zou je hier nog een hoofdletter van willen maken?
> 
> ![image](https://user-images.githubusercontent.com/86714970/130818946-67bc112f-5a0d-49e0-945d-f53396a5ddc1.png)

Gedaan en staat straks op staging.

**Comment by RenildeMendoo** [comment]
> > Punt 2: Tabblad gastgezinnen
> > Onder het tabblad gastgezinnen zijn nu 'Alle GG', 'Beschikbare GG', 'Onbeschikbare GG', 'Nieuwe GG'
> > Kan dit aangepast worden naar: 'Alle GG', 'Beschikbare GG', 'Niet beschikbare GG' en 'Nieuw GG'?
> 
> Nee dit kan helaas niet. Want er is net een nieuw tabblad bijgekomen dus het wringt nu... zie de issue #52

Zou dan 'onbeschikbaar' vervangen kunnen worden door 'Niet beschikbaar'?

**Comment by RenildeMendoo** [comment]
> > Punt 3: het vele gebruik van het woord 'updates'
> > Wat je ook al noemde in een ander Issue. Waar ik het dus 100% mee eens ben en af en toe ook helemaal gek van word.
> > Ik zie dat je op de beginpagina 'Dier' daar het woord 'update' regelmatig hebt weggehaald (super fijn):
> > ![image](https://user-images.githubusercontent.com/86714970/130818499-a9597afd-c4ed-4a09-880b-1fadcc8ac041.png)
> > Maar als ik met m'n muis op een icoontje ga staan, komt er nog steeds 'eigenaar update vervolg' te staan (of bijv hulpverlener update). Zou het beter zijn om daar ook het woord 'update' steeds weg te halen? Of maakt dat weinig uit en moeten wij in het team gewoon afleren om het woord 'update' overal maar voor te gebruiken?
> 
> eh, nou, bijvoorbeeld in deze zin dus:
> _EIGENAAR UPDATE. Dit dier is langer dan twee weken in het project, maar er is geen eigenaar update._
> Hier gebruik ik het dus ook door elkaar. In de eerste geval is het letterlijk een update, in het tweede geval is het een bericht, of notitie, iets dergelijks. Dan moet ik dus een andere zelfstandig naamwoord hebben. Uhm. Maar daarvoor snap ik het niet goed genoeg!!!
> 
> Weet je wat: leef je uit met deze zinnen.
> 
> ```
> 			if (!$uc['has_owner_update']) {
> 				 $icons[] = Animal::make_icon_row(["female"], 'EIGENAAR UPDATE. Dit dier is langer dan twee weken in het project, maar er is geen eigenaar update.');
> 				$prompts[] =  "Eigenaar eerste contact.";
> 			} else if(!$uc['owner_update_on_time']) {
> 				$icons[] = Animal::make_icon_row(['repeat',"female"], 'EIGENAAR UPDATE VERVOLG. Er was eerder contact met de eigenaar, maar dat is langer dan twee weken geleden.');
> 				$prompts[] = "Eigenaar vervolg contact.";
> 			}
> 		endif; // needs owner update
> 
> 		if ($uc['needs_caregiver_update']) :
> 			if (!$uc['has_caregiver_update'] || !$uc['caregiver_update_on_time']){
> 				$uc['in_todo_list'] = true;
> 			}
> 			if (!$uc['has_caregiver_update']) {
> 				$icons[] = Animal::make_icon_row(["users"], 'HULPVERLENER UPDATE. Dit dier is langer dan twee maanden in het project, maar de hulpverlening is nog niet gesproken.');
> 				$prompts[] = "Hulpverlening eerste contact.";
> 			} else if(!$uc['caregiver_update_on_time']) {
> 				$icons[] = Animal::make_icon_row(['repeat',"users"], 'HULPVERLENER UPDATE. Er was eerder contact met de hulpverlening, maar dat is langer dan twee maanden geleden.');
> 				$prompts[] = "Hulpverlening vervolg contact.";		
> 			}
> 		endif; // needs caregiver update
> 		
> 		if ($uc['needs_pension_guest_update']) :
> 			if (!$uc['has_pension_guest_update'] || !$uc['pension_guest_update_on_time']){
> 				$uc['in_todo_list'] = true;
> 			}
> 			if (!$uc['has_pension_guest_update']) {
> 				$icons[] = Animal::make_icon_row(["home"], 'GASTGEZIN/PENSION UPDATE. Dit dier is langer dan twee maanden in het project, maar het verblijf is nog niet gesproken.');
> 				$prompts[] = "Verblijf eerste contact.";
> 			} else if(!$uc['pension_guest_update_on_time']) {
> 				$icons[] = Animal::make_icon_row(['repeat',"home"], 'GASTGEZIN/PENSION UPDATE. Er was eerder contact met het verblijf, maar dat is langer dan twee maanden geleden.');
> 				$prompts[] = "verblijf gastgezin/pension vervolg contact.";		
> 			}
> 		endif; // needs pension guest update
> 
> 		if ($uc['needs_jaarevaluatie_update']) :
> 			if (!$uc['has_jaarevaluatie_update']){
> 				$uc['in_todo_list'] = true;
> 			}
> 			if (!$uc['has_jaarevaluatie_update']) {
> 				$icons[] = Animal::make_icon_row(["sign-out"], 'JAAREVALUATIE UPDATE. Dit dier is langer dan tien maanden in het project, het wordt tijd voor een evaluatiegesprek.');
> 				$prompts[] = "Jaarevaluatie nodig.";
> 			} 
> 		endif; // needs jaarevaluatie update
> ```

Hmm, dit is denk ik ook wel prima zo :) ik kan nu niet zo snel alternatieven bedenken

**Comment by sjerpbouwtsites** [comment]
Verschijnt weldra dan op staging.
