### ISSUE TITLE
En zou je de 'onzin onzin onzin' kunnen vervangen door 'onbekend'? Dat staat wat mooier ;)

### ISSUE THREAD

**Issue by sjerpbouwtsites** [sjerpbouwtsites/blijfvanmijndier#71]
En zou je de 'onzin onzin onzin' kunnen vervangen door 'verloren'? Dat staat wat mooier ;)

_Originally posted by @RenildeMendoo in https://github.com/sjerpbouwtsites/blijfvanmijndier/issues/57#issuecomment-900964922_

**Comment by sjerpbouwtsites** [comment]
Staat NIET op staging, staat op productie @RenildeMendoo

**Comment by RenildeMendoo** [comment]
@sjerpbouwtsites ik zie het, netjes. Dankjewel!
