### ISSUE TITLE
kleuren dieren updates bijtijds of niet aanpassen

### ISSUE THREAD

**Issue by sjerpbouwtsites** [sjerpbouwtsites/blijfvanmijndier#72]
Yeahhh cool, ik zie het idd! :D 
Netjes!

En zijn er dan te weinig 'mendoo' kleuren om elk type update een eigen kleur te geven? Of begrijp ik het verkeerd? 
Dus bijv 'eigenaar contact vervolg' paars, 'hulpverlening contact' rood, 'gastgezin/pension contact' oranje, 'jaarevaluatie' zwart? 
Dan kom ik wel mooi uit met de aantal soorten updates, of ben ik dan weer helemaal in de war :p Dat kan ook hoor! 

Het team (en ik ook) vond het met al die kleuren wel heel duidelijk/overzichtelijk. Maar mss is het ook wel teveel van het goede, dat kan ook natuurlijk. Zelf vind ik het met het groene (turqoise) handje wel heel mooi staan. 
Misschien een tussenweg door bijvoorbeeld de tekentjes zelf een kleurtje te geven (zoals het groene handje ook gekleurd is) en de achtergrond grijs te houden?

_Originally posted by @RenildeMendoo in https://github.com/sjerpbouwtsites/blijfvanmijndier/issues/62#issuecomment-905527434_

**Comment by sjerpbouwtsites** [comment]
@RenildeMendoo 
![afbeelding](https://user-images.githubusercontent.com/34159539/132335002-478ba516-5cbb-4fba-b4a5-3cb06b0a2a1a.png)

**Comment by RenildeMendoo** [comment]
Jaaa super vet! Dit was precies wat ik in gedachte had :D

**Comment by sjerpbouwtsites** [comment]
Staat op staging @RenildeMendoo

**Comment by RenildeMendoo** [comment]
Aaaah bij mij staat ie nog niet op staging:
![image](https://user-images.githubusercontent.com/86714970/132501528-157f1268-6114-4b29-b559-4e4a8ac3dad4.png)
