### ISSUE TITLE
Livegang 8 september

### ISSUE THREAD

**Issue by sjerpbouwtsites** [sjerpbouwtsites/blijfvanmijndier#73]
Sjerp van Wouden, voor al uw bugs en miskleunen. Het is weer 'gelukt'!

@RenildeMendoo

**Comment by RenildeMendoo** [comment]
Jaaa super! De twee 'grote' aanpassingen lijken te werken; bestanden kunnen we weer uploaden en bekijken. En je ziet bij een GG op de pagina welke eigen dieren ze hebben. Super :D Dankjewel! Als er nog andere bugs te voorschijn komen, hoor je van me!

**Comment by RenildeMendoo** [comment]
We hebben er eentje gevonden! Op de google maps kaart zijn alle pinnetjes vervangen door gekke plaatjes:
![image](https://user-images.githubusercontent.com/86714970/132537840-6d59d4dc-bee5-48a8-a167-fd2093809718.png)

**Comment by sjerpbouwtsites** [comment]
Ook bizar hoe dit zich 'in ene' uit. Kwam ie dus eerst bij mij uit de cache. nou ja

**Comment by sjerpbouwtsites** [comment]
Fix. Ok ik zet dit bij die migratiegids van me. Dit is dus één van die vele valkuilen.

**Comment by sjerpbouwtsites** [comment]
> 
> 
> Jaaa super! De twee 'grote' aanpassingen lijken te werken; bestanden kunnen we weer uploaden en bekijken. En je ziet bij een GG op de pagina welke eigen dieren ze hebben. Super :D Dankjewel! Als er nog andere bugs te voorschijn komen, hoor je van me!

@RenildeMendoo Het blijft echt fijn hoe enthousiast je bent, zelfs al veroorzaak ik met enige regelmaat bugs 🖤
